stages:
- build
- create-debian-package

Package Docker Image:
  stage: build
  artifacts:
   name: build-debian
   paths:
    - /builds
    - /etc/e2guardian
    - /usr/sbin/e2guardian
    - /usr/share/e2guardian   
  image: amd64/debian:stable
  variables:
   OS: "debian"
  script:
    - apt update
    - apt-get -y upgrade
    - apt install --no-install-recommends --no-install-suggests -y curl unzip base-files automake base-passwd
      bash coreutils dash debianutils diffutils dpkg e2fsprogs findutils grep gzip hostname ncurses-base
      libevent-pthreads-* libevent-dev ncurses-bin perl-base sed login sysvinit-utils tar bsdutils
      mount util-linux libc6-dev libc-dev gcc g++ make dpkg-dev autotools-dev debhelper dh-autoreconf dpatch
      libclamav-dev libpcre3-dev zlib1g-dev pkg-config libssl-dev libssl1.1 git ca-certificates lsb-release
    - cd /builds/fredbcode/e2guardian && ./autogen.sh && ./configure  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian'
      '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes'
      '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info'
      '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'
    - make install && cp src/e2guardian /usr/sbin/ && mkdir -p /var/log/e2guardian
      && mkdir -p /usr/share/e2guardian/languages && cp -Rf data/languages /usr/share/e2guardian/ && cp data/*.gif /usr/share/e2guardian/ && cp data/*swf /usr/share/e2guardian/
      && cp -Rf configs/* /etc/e2guardian/
      && adduser --no-create-home --system e2guardian
      && addgroup --system e2guardian

Create Package:
  stage: create-debian-package
  image: amd64/debian:stable
  variables:
    VFULL: $(/usr/sbin/e2guardian -v | sed -n 1p | cut -d " " -f 2`)
    OS: "debian"
  after_script:
    - export SIZE=$(stat -c %s e2${OS}_package/data)
    - echo ${SIZE}
    - 'sed -i "s/Installed-Size:.*$/Installed-Size: $(SIZE)"/g" e2${OS}_package/control/control'
  script:
    - cd /builds/fredbcode/e2guardian 
    - apt update && apt install --no-install-recommends --no-install-suggests -y curl git ca-certificates lsb-release
    - git clone https://github.com/fredbcode/scripts
    - cd scripts/${OS}_package && cp /usr/sbin/e2guardian e2${OS}_package/data/usr/sbin && cp -Rf /etc/e2guardian/* e2${OS}_package/data/etc/ && cp -rf /usr/share/e2guardian e2${OS}_package/data/usr/share
    - find e2${OS}_package/ -type f -name Makefil* -delete
    - find e2${OS}_package/ -type f -name *.in -delete
    - SIZE=$(stat -c %s e2${OS}_package/data) &&  sed -i "s/Installed-Size:.*$/Installed-Size:\ $(SIZE)/g" e2"${OS"_package/control/control
    - VFULL=`/usr/sbin/e2guardian -v | sed -n 1p | cut -d " " -f 2` && sed -i "s/Version:.*$/Version:\ $(VFULL]/g" e2"$OS"_package/control/control 
    - cp /builds/fredbcode/e2guardian/data/scripts/e2guardian.service /builds/fredbcode/e2guardian/e2"${OS}"_package/data/lib/systemd/system
    - cat e2"$OS"_package/control/control && ./rebuild.sh e2"$OS"_package
