stages:
- build:debian
- create-debian-package

Package Docker Image:
  stage: build:debian
  artifacts:
   name: build-debian
   paths:
    - /builds   
  image: amd64/debian:stable
  variables:
   OS: "debian"
  script:
    - apt update
    - apt-get -y upgrade
    - apt install --no-install-recommends --no-install-suggests -y curl unzip base-files automake base-passwd
      bash coreutils dash debianutils diffutils dpkg e2fsprogs findutils grep gzip hostname ncurses-base
      libevent-pthreads-* libevent-dev ncurses-bin perl-base sed login sysvinit-utils tar bsdutils
      mount util-linux libc6-dev libc-dev gcc g++ make dpkg-dev autotools-dev debhelper dh-autoreconf dpatch
      libclamav-dev libpcre3-dev zlib1g-dev pkg-config libssl-dev libssl1.1 git ca-certificates lsb-release
    - cd /builds/fredbcode/e2guardian && ./autogen.sh && ./configure  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian'
      '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes'
      '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info'
      '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'
    - make 

Create Package:
  stage: create-debian-package
  image: amd64/debian:stable
  variables:
    VFULL: $(/usr/sbin/e2guardian -v | sed -n 1p | cut -d " " -f 2`)
    PACKPATH: "/builds/fredbcode/e2guardian"
    PACKDST: "/builds/fredbcode/e2guardian/scripts/debian_package/e2debian_package"
    OS: "debian"
  script:
    - cd /builds/fredbcode/e2guardian 
    - apt update && apt install --no-install-recommends --no-install-suggests -y curl git ca-certificates lsb-release
    - git clone https://github.com/fredbcode/scripts
    - cp ${PACKPATH}/src/e2guardian ${PACKDST}/data/usr/sbin/e2guardian
    - cp -Rf ${PACKPATH}/configs ${PACKDST}/data/etc/e2guardian/
    - mkdir -p  ${PACKPATH}/share/e2guardian/languages
    - cp -Rf ${PACKPATH}/data/languages ${PACKDST}/data/usr/share/e2guardian/
    - cp ${PACKPATH}/data/*.gif ${PACKDST}/data/usr/share/e2guardian/
    - cp ${PACKPATH}/data/*swf ${PACKDST}/data/usr/share/e2guardian/
    - cp ${PACKPATH}/data/scripts/e2guardian.service ${PACKDST}/data/lib/systemd/system
    - find ${PACKDST}/ -type f -name Makefil* -delete
    - find ${PACKDST}/ -type f -name *.in -delete
    - export SIZE=$(stat -c %s ${PACKDST}/data) &&  sed -i "s/Installed-Size:.*$/Installed-Size:\ $(SIZE)/g" ${PACKDST}/control/control
    - export VFULL=`${PACKDST}/data/usr/sbin/e2guardian -v | sed -n 1p | cut -d " " -f 2` && sed -i "s/Version:.*$/Version:\ $(VFULL]/g" ${PACKDST}/control/control 
    - cd ${PACKDST} && cd .. && ./rebuild.sh e2"$OS"_package
